django/blog/blog/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = "blog"

urlpatterns = [
    # http://127.0.0.1:8000/blog/ 리스트
    path("", views.list, name="list"),
    # http://127.0.0.1:8000/blog/post/1 : detail
    path("post/<int:post_id>", views.detail, name="detail"),
    # http://127.0.0.1:8000/blog/post/create
    path("post/create/", views.create, name="create"),
    # http://127.0.0.1:8000/blog/post/modify/1
    path("post/modify/<int:post_id>", views.modify, name="modify"),
    # http://127.0.0.1:8000/blog/post/delete/1
    path("post/delete/<int:post_id>", views.delete, name="delete"),
    # 댓글
    # http://127.0.0.1:8000/blog/post/comment/<post_id>
    path("post/comment/<int:post_id>", views.comment_create, name="comment_create"),
    # 좋아요
    # http://127.0.0.1:8000/blog/post/like/<post_id>
    path("post/like/<int:post_id>", views.post_like, name="post_like"),
]

django/blog/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = "common"

urlpatterns = [
    path("register/", views.register, name="register"),
    # login 처리를 하는 뷰가 함수형뷰가 아니라 클래스뷰임
    # 클래스뷰를 함수형처럼 사용하려면 as_view() 사용
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="common/login.html",
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    # 기존 비밀번호 변경 후 세션 값 다시 담아줌
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="common/password_change.html",
            success_url=reverse_lazy("index"),
        ),
        name="password_change",
    ),
    # 비밀번호 초기화
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="common/password_reset.html",
            email_template_name="common/password_reset_email.txt",
            success_url=reverse_lazy("common:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="common/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="common/password_reset_confirm.html",
            success_url=reverse_lazy("common:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="common/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

django/blog/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("", RedirectView.as_view(url="/blog"), name="index"),
    path("common/", include("common.urls")),
]

# 파일업로드 URL 환경설정 작업(settings.py)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/board/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    path("", RedirectView.as_view(url="/board/")),
]

django/blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to="image")
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name="likes", blank=True)
    tags = TaggableManager()

    # auto_now_add : 처음에만 날짜 입력
    # auto_now : 수정될 때마다 날짜 입력

    # 리스트 추출 시 작성일자의 내림차순으로 추출
    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.title


class Comment(models.Model):
    """
    user, post, content, 작성날짜, 수정날짜 정보
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return "%s - %s" % (self.id, self.user)

django/blog/common/models.py
from django.db import models

# Create your models here.

django/blog/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = "__all__"
        fields = ["title", "content", "image", "tags"]

django/blog/common/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):

    email = forms.EmailField(label="이메일", help_text="사용할 이메일을 입력해 주세요")

    class Meta:
        model = User
        fields = ["username", "email"]
        labels = {"username": "아이디"}

django/blog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse


def comment_create(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        content = request.POST.get("content").strip()

        # CommentForm을 안쓰는 방법 (1번, 2번)
        # 1번 방법
        # Comment.objects.create(user=request.user, post=post, content=content)

        # 2번 방법 : 이 방식은 save() 까지 해주어야 함
        comment = Comment(user=request.user, post=post, content=content)
        comment.save()

        # post 일 때 가는 경로
        return redirect("blog:detail", post_id)

    # get 일 때 가는 경로
    return redirect("blog:detail", post_id)


def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect("blog:list")


def modify(request, post_id):

    post = get_object_or_404(Post, id=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("blog:detail", post.id)

    else:
        form = PostForm(instance=post)
    return render(request, "blog/modify.html", {"form": form, "post": post})


@login_required(login_url="common:login")
def create(request):
    if request.method == "POST":
        # 폼에 post 로 넘어오는 내용 담기
        form = PostForm(request.POST, request.FILES)
        # 폼 유효성 검증
        if form.is_valid():
            # 유효성 통과 하면 저장
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # 태그 저장
            form.save_m2m()

            # 리스트로 이동
            return redirect("blog:list")
            # return redirect("blog:detail", post.id)
    else:
        form = PostForm()

    return render(request, "blog/create.html", {"form": form})


def list(request):
    # Post 전체 조회

    page = request.GET.get("page", 1)

    posts = Post.objects.all()

    paginator = Paginator(posts, 5)
    page_obj = paginator.get_page(page)

    context = {"posts": page_obj}

    return render(request, "blog/list.html", context)


def detail(request, post_id):

    post = get_object_or_404(Post, id=post_id)

    # 로그인 유저가 해당 게시물에 좋아요 했는지 안했는지 확인
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    return render(request, "blog/post.html", {"post": post, "is_liked": is_liked})


def post_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # 로그인 유저가 해당 게시물에 좋아요 했는지 안했는지 확인
    is_liked = post.likes.filter(id=request.user.id).exists()

    is_liked_change = False

    if is_liked:
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        is_liked_change = True

    return JsonResponse({"likes": post.likes.count(), "is_liked": is_liked_change})

django/blog/common/views.py
from django.shortcuts import render, redirect
from .forms import UserForm


def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("common:login")

    else:
        form = UserForm()

    return render(request, "common/register.html", {"form": form})

django/blog/templates/blog/create.html
{% extends "base.html" %}
{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {% include "form_errors.html" %}
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group mb-3">
            <label for="title">제목</label>
            <input type="text" name="title" id="title" class="form-control" value="{{form.title.value|default_if_none:''}}"/>
          </div>
          <!-- 오류 표시 영역-->
          <div class="form-group mb-3">
            <label for=" content">내용</label>
            <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
          </div>
          <div class="form-group mb-3">
            <label for="subject">이미지</label>
            <input type="file" name="image" id="image" class="form-control"/>
          </div>
          <div class="form-group mb-3">
            <label for="tags">태그</label>
            <input type="text" name="tags" id="tags" class="form-control" value="{{form.tags.value|default_if_none:''}}"/>
            <small>태그는 콤마로 구분해서 입력하세요</small>
          </div>
          <input type="submit" value="새글작성" class="btn btn-primary"/>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

django/blog/templates/blog/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div>
          <a class="btn btn-danger" href="{% url "blog:create" %}">새글작성</a>
        </div>
        <!-- Post preview-->
        {% for post in posts %}
          <div class="post-preview">
            <a href="{% url "blog:detail" post.id %}">
              <h2 class="post-title">
                <!-- title -->
                {{post.title}}
              </h2>
              <h3 class="post-subtitle">
                <!-- content -->
                {{post.content|truncatechars:100}}
              </h3>
            </a>
            <p class="post-meta">
              Posted by
              <a href="#!">
                <!-- user -->
                {{post.user}}
              </a>
              <!-- created_at -->
              {{post.created_at}}

            </p>
          </div>
          <!-- Divider-->
          <hr class="my-4"/>
        {% endfor %}
        <!-- Pager-->
        <div class="d-flex justify-content-end mb-4">
          {% if posts.has_previous %}
            <a class="btn btn-primary text-uppercase" href="?page={{posts.previous_page_number}}">← Previous Posts</a>
          {% endif %}
          <a class="btn btn-primary text-uppercase" href="#!">{{posts.number}}/{{posts.paginator.num_pages}}</a>
          {% if posts.has_next %}
            <a class="btn btn-primary text-uppercase" href="?page={{posts.next_page_number}}">Next Posts →</a>
          {% endif %}
        </div>
      </div>
    </div>
  {% endblock content %}

django/blog/templates/blog/modify.html
{% extends "base.html" %}
{% block content %}
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {% include "form_errors.html" %}
        <!-- file 들어가면 무조건 enctype 바꿔야함 -->
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group mb-3">
            <label for="title">제목</label>
            <input type="text" name="title" id="title" class="form-control" value="{{form.title.value|default_if_none:''}}"/>
          </div>
          <div class="form-group mb-3">
            <label for="content">내용</label>
            <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value|default_if_none:""}}</textarea>
          </div>
          <div class="form-group mb-3">
            <label for="image">이미지</label>
          </div>
          {% if form.image.value %}
            <div class="row mb-2">
              <div class="col-auto">현재</div>
              <div class="col-auto">
                <a href="{{form.image.vlaue.url}}">
                  <span>{{form.image.value.name}}</span>
                </a>
              </div>
              <div class="col-auto">
                <input type="checkbox" name="image-clear" id="image-clear_id" class="form-check-input">
                <label for="image-clear_id" class="form-check-label">취소</label>
              </div>
            </div>
          {% endif %}
          <div class="form-group mb-2">
            변경<input type="file" name="image" id="image" class="form-control"/>
          </div>

          <div class="form-group mb-2">
            <input type="submit" value="수정" class="btn btn-primary"/>
            <a href="{% url "blog:delete" post.id %}" class="btn btn-danger">삭제</a>
            <a href="{% url "blog:list" %}" class="btn btn-info">목록</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

django/blog/templates/blog/post.html
{% extends "base.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static "css/post.css" %}">
{% endblock css %}
{% block content %}
  <article class="mb-4">
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="row">
            <div class="col-md-10">
              <h3 class="border-bottom pb-2">
                <!-- 제목 -->
                {{post.title}}
              </h3>
            </div>
          </div>
          <div class="row">
            <div class="col-md-10">
              <!-- 이미지 보여주기 -->
              {% if post.image %}
                <img src="{{post.image.url}}" alt="" class="mx-auto d-block">
              {% endif %}
            </div>
          </div>
          <div class="row">
            <div class="col-md-10">
              <!-- 본문 보여주기 -->
              <p>{{post.content}}</p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-10">
              <a href="{% url "blog:modify" post.id %}" class="btn btn-info">수정</a>
              <a href="{% url "blog:list" %}" class="btn btn-success">목록</a>
            </div>
          </div>

          {% include "like.html" %}

          <!-- taggit -->
          <div class="row mt-5">
            <div class="col-md-10">
              {% for tag in post.tags.all %}
                <span class="badge rounded-pill text-bg-dark">#{{tag.name}}</span>
              {% endfor %}
            </div>
          </div>

          <!-- 댓글 목록 처리 -->
          {% if post.comment_set.count > 0 %}
            <div class="row mt-5">
              <div class="col-md-10">
                <div class="card mb-5">
                  <div class="card-header">
                    <i class="fa-regular fa-comments"></i>
                    Comments
                  </div>
                  <!-- 댓글 반복 -->
                  {% for comment in post.comment_set.all %}
                    <div class="card-body">
                      <h5 class="card-title">
                        <!-- 댓글 내용 -->
                        {{comment.content}}
                      </h5>
                      <div class="card-text text-end fs-6 bg-light">
                        <!-- 댓글작성자(댓글작성일시) -->
                        {{comment.user}}({{comment.created_at}})
                      </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endif %}

          <!-- 댓글 등록 -->
          {% if user.is_authenticated %}
            <div class="row mt-5">
              <div class="col-md-10">
                <form action="{% url "blog:comment_create" post.id %}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <textarea name="content" id="content" class="form-control" rows="7"></textarea>
                  </div>
                  <div class="form-group d-grid">
                    <button type="submit" class="btn btn-secondary">댓글등록</button>
                  </div>
                </form>
              </div>
            </div>
          {% endif %}

        </div>
      </div>
    </div>
  </article>
{% endblock content %}
{% block script %}
  <script src="{% static "js/post.js" %}"></script>
{% endblock script %}